---
title: "ML Assignment 1"
author: "Sean Bradford"
output:
  html_document:
    df_print: paged
---
1. & 2.
```{r}
nfl_data=read.csv('C:\\Users\\Sean\\OneDrive\\Desktop\\Grad School\\Machine Learning\\Module 2 - Intro to R\\nfl_19to22data.csv')

# Data Source: https://www.advancedsportsanalytics.com/nfl-raw-data
nfl_data
```
The dataset contains statistics for passing, rushing, and receiving per game for NFL players since 2019.

3.
```{r}
summary(nfl_data[,c("player","team","pass_yds","pass_td")])
```
Qualitative Variables:'player' & 'team'
Quantitative Variables: 'pass_yds' & 'pass_td'

4.
```{r}
library(dplyr)
nfl_data=nfl_data%>%mutate(pass_cmp=(pass_cmp/pass_att))
head(nfl_data)
summary(nfl_data$pass_cmp)

```
Changed variable pass_cmp to return the ratio of passes completed instead of the total number of passes completed.

5.
```{r}
plot(nfl_data$rush_yds)
```

```{r}
plot(nfl_data$pass_yds)
```
Created scatterplots for rushing yards and passing yards per player.
