---
title: "Predicting Run Direction with K-NN Algorithm"
author: "Sean Bradford"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
rm(list=ls())

library(FNN)
library(ISLR)
library(caret)
library(dplyr)

data=read.csv("C:\\Users\\Sean\\OneDrive\\Desktop\\Grad School\\Machine Learning\\Final\\train.csv")

# create data frame for Colts possessing ball
colts.data=data%>%filter(data$PossessionTeam=="IND")

# create data frame for Colts running backs
colts.run=colts.data%>%filter(colts.data$Position=="RB")

head(colts.run)
```

```{r}
summary(colts.run)
```


```{r}
# isolate predictor variables
colts.run2=colts.run[,c("X","Y","Orientation","PlayDirection")]


# normalize data using z-score
norm1=preProcess(colts.run2,method=c('center','scale'))
colts.norm=predict(norm1,colts.run2)
```

```{r}
# partition the data 80/20
set.seed(111)
train.index=createDataPartition(colts.norm$PlayDirection,p=.8,list=FALSE)

train=colts.norm[train.index,]
test=colts.norm[-train.index,]

train.predictors=train[,-4]
test.predictors=test[,-4]

train.labels=train[,4]
test.labels=test[,4]
```

```{r}
# test model using k=4
pred.test.label=knn(train.predictors,test.predictors,cl=train.labels,k=4)
head(pred.test.label)
```

```{r}
# determine optimal k value
search.grid=expand.grid(k=c(1:20))
model=train(PlayDirection~X+Y+Orientation,data=colts.norm,method="knn",tuneGrid=search.grid)

model
```

```{r}
# evaluate confusion matrix & determine model's fitness

library('gmodels')
pred.test.label1=knn(train.predictors,test.predictors,cl=train.labels,k=13)
xyz=CrossTable(x=test.labels,y=pred.test.label1,prop.chisq=FALSE)
xyz
```

```{r}
# create variables for true positives, false positives, true negatives, false negatives, total rows
TP=96
FP=10
TN=94
FN=11
N=211

# calculate model accuracy
accuracy=(TP+TN)/N
accuracy

# calculate model recall
recall=TP/(TP+FN)
recall

# calculate model precision
precision=TP/(TP+FP)
precision

# calculate model specificity
specificity=TN/(TN+FP)
specificity
```


```{r}
# predict run direction during game
game.scenario=data.frame(X=105,Y=25,Orientation=21)

game.prediction=knn(train.predictors,game.scenario,cl=train.labels,k=13)
head(game.prediction)
```



